name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hellow world"
      - name: print goodgye
        run: echo "Done - bye!"
